import React from 'react';
import './index.css';

class Buttons extends React.Component {
    render() {
      return (
        <div id="calculatorButtons">
          <button 
            id="clear" 
            onClick={this.props.allClear}          
            value="AC"
          >
            AC
          </button>
          <button 
            id="divide" 
            onClick={this.props.operatorClick}          
            value="/"
            className="operand"
          >
            /
          </button>
          <button 
            id="multiply" 
            onClick={this.props.operatorClick}          
            value="*"
            className="operand"
          >
            *
          </button>
          <button 
            id="seven" 
            onClick={this.props.numberClick}          
            value="7"
            className="number"
          >
            7
          </button>
          <button 
            id="eight" 
            onClick={this.props.numberClick}                   
            value="8"
            className="number"
          >
            8
          </button>
          <button 
            id="nine" 
            onClick={this.props.numberClick}          
            value="9"
            className="number"
          >
            9
          </button>
          <button 
            id="subtract" 
            onClick={this.props.operatorClick}          
            value="-"
            className="operand"
          >
            -
          </button>
          <button 
            id="four" 
            onClick={this.props.numberClick}          
            value="4"
            className="number"
          >
            4
          </button>
          <button 
            id="five" 
            onClick={this.props.numberClick}          
            value="5"
            className="number"
          >
            5
          </button>
          <button 
            id="six" 
            onClick={this.props.numberClick}          
            value="6"
            className="number"
          >
            6
          </button>
          <button 
            id="add" 
            onClick={this.props.operatorClick}          
            value="+"
            className="operand"
          >
            +
          </button>
          <button 
            id="one" 
            onClick={this.props.numberClick}          
            value="1"
            className="number"
          >
            1
          </button>
          <button 
            id="two" 
            onClick={this.props.numberClick}          
            value="2"
            className="number"
          >
            2
          </button>
          <button 
            id="three" 
            onClick={this.props.numberClick}          
            value="3"
            className="number"
          >
            3
          </button>
          <button 
            id="equals" 
            onClick={this.props.equalsClick}          
            value="="
          >
            =
          </button>
          <button 
            id="zero" 
            onClick={this.props.numberClick}          
            value="0"
            className="number"
          >
            0
          </button>
          <button 
            id="decimal" 
            onClick={this.props.decimalClick}          
            value="."
            className="number"
          >
            .
          </button>
        </div>            
      )
    }
  }
   
  export default Buttons;  